name: Test tap-pokemon

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
      PIP_CONSTRAINT: .github/workflows/constraints.txt
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5.0.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install --python '${{ steps.setup-python.outputs.python-path }}' poetry
        poetry --version

    - name: Install tox
      run: |
        pipx install --python '${{ steps.setup-python.outputs.python-path }}' tox
        tox --version

    - name: Run tests with Tox
      run: |
        tox -e pytest
