name: Test tap-pokemon

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
      PIP_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    steps:
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-python@v5.2.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@v3
      with:
        version: ">=0.4.18"
    - run: uvx tox -e $(echo py${{ matrix.python-version }} | tr -d .)
